---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: IngressHostnamePrefix
metadata:
  name: ingress-hostname-prefix
spec:
  match:
    kinds:
      - apiGroups: ["networking.k8s.io"]
        kinds: ["Ingress"]
  parameters:
    allowedIngressHostnames: "azingress"